Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port", guest: 3000, host: 3000

  config.vm.provider "virtualbox" do |v|
    v.name = "dev-vagrant"
    v.memory = 2048
    v.cpus = 2
  end
  
  # For windows
  # config.vm.synced_folder "../data", "/vagrant_data"
  # For Unix
  config.vm.synced_folder "/Users/jc/Documents/deps/vagrant/shared", "/home/vagrant/shared_folder"


  # Provisioning with shell script
  config.vm.provision :shell, :path => "./provision.sh"
end
