#!/bin/sh
while read file
do
    case "$1" in
    "w")
      WALLPAPER_DIR=$HOME/.wallpapers
      echo $(basename "$file") > $WALLPAPER_DIR/.current_wallpaper
      hsetroot -cover "$file"
      ;;
    "p")
      hsetroot -cover "$file"
      ;;
    "r")
      convert -rotate 90 "$file" "$file" ;;
    "R")
      convert -rotate -90 "$file" "$file" ;;
    "f")
      convert -flop "$file" "$file" ;;
    "y")
      echo -n "$file" | xclip -selection clipboard && notify-send "$file copied to clipboard" & ;;
    "d")
      # [ "$(echo -e "No\\nYes" | rofi -dmenu -i -p "Really delete $file?")" = "Yes" ] && rm "$file" && notify-send "$file deleted." ;;
      gio trash "$file" && notify-send "$file deleted." ;;
    "g")
      gimp "$file" & ;;
    esac
done
