#!/bin/sh
while read file
do
    case "$1" in
		"r")
			convert -rotate 90 "$file" "$file" ;;
		"R")
			convert -rotate -90 "$file" "$file" ;;
		"f")
			convert -flop "$file" "$file" ;;
		"y")
			echo -n "$file" | xclip -selection clipboard &&
			notify-send "$file copied to clipboard" & ;;
		"d")
			[ "$(echo -e "No\\nYes" | rofi -dmenu -i -p "Really delete $file?")" = "Yes" ] && rm "$file" && notify-send "$file deleted." ;;
		"g")
			gimp "$file" & ;;
    esac
done
